### PR TITLE
Update icon of the vscode extension

### PR DESCRIPTION
**Pull request by limemloh**
## Purpose

Update Icon of the VS Code extension to better support dark themes.
Closing #67 

Default light theme:
image
Default dark theme:
image

### CODE REVIEW

**Comment by abizjak** [comment]
It would probably make sense to make the inner C bigger. Now it is quite tiny in the middle.

**Comment by limemloh** [comment]
Here's the logo without text.
image
image

This seems better, and the Concordium name is visible everywhere anyway.

**Review by Bargsteen — APPROVED** [review]
Looks good!

**Comment by abizjak** [comment]
> Here's the logo without text.
> 
> 
> 
> image
> 
> image
> 
> 
> 
> This seems better, and the Concordium name is visible everywhere anyway.

Yes I agree this is better. Let's go with this one.

**Review by abizjak — APPROVED** [review]
The one without text looks good.

**Pull request merged**
